### ISSUE TITLE
Zemax parsing errors if TYPE is not set on surfaces

### ISSUE THREAD

**Issue by ajeddeloh** [mjhoptics/ray-optics#9]
Edmund optics omits the TYPE line on their zmx files which causes the parser to fail. Parsing succeeds if I add a line:

`TYPE STANDARD`

to every surface definition.

Lens on edmund I was trying to load:
https://www.edmundoptics.com/p/11-with-100mm-and-100mm-efl-achromats-30mm-achromatic-pair/12126/

Traceback:

```
[andrew@lime ~]$ rayoptics
close event received: <PyQt5.QtWidgets.QMdiSubWindow object at 0x7f05a9fb7160>
Traceback (most recent call last):
  File "/home/andrew/.local/lib/python3.8/site-packages/rayoptics/qtgui/rayopticsapp.py", line 235, in file_action
    self.open_file(filename)
  File "/home/andrew/.local/lib/python3.8/site-packages/rayoptics/qtgui/rayopticsapp.py", line 262, in open_file
    opt_model = cmds.open_model(file_name, **kwargs)
  File "/home/andrew/.local/lib/python3.8/site-packages/rayoptics/gui/appcmds.py", line 77, in open_model
    opm, import_info = zmxread.read_lens_file(file_name, **kwargs)
  File "/home/andrew/.local/lib/python3.8/site-packages/rayoptics/zemax/zmxread.py", line 62, in read_lens_file
    opt_model, info = read_lens(filename, inpt, **kwargs)
  File "/home/andrew/.local/lib/python3.8/site-packages/rayoptics/zemax/zmxread.py", line 100, in read_lens
    process_line(opt_model, line, i+1)
  File "/home/andrew/.local/lib/python3.8/site-packages/rayoptics/zemax/zmxread.py", line 138, in process_line
    if s.z_type != 'PARAXIAL':
AttributeError: 'Surface' object has no attribute 'z_type'
Aborted (core dumped)
```

The offending code is here:

https://github.com/mjhoptics/ray-optics/blob/master/src/rayoptics/zemax/zmxread.py#L138

Perhaps interfaces should have a `z_type` of `STANDARD` by default? Let me know if you can't reproduce or need any more information.

P.S. This is a great project. I'm trying to teach myseld geometric optics and it's invaluable to be able to try things out. Thanks for all the work that's made this possible.

**Comment by mjhoptics** [comment]
Thanks for reporting this. It should be straightforward to fix. The importer is completely reverse-engineered by someone (me) who isn't a Zemax user, so if you come across any other Zemax import problems, please report them. Thanks!

**Comment by ajeddeloh** [comment]
I wrote a quick and dirty converter to split out zmx's from a zmf.

https://gist.github.com/ajeddeloh/0fad161538e140770308cbfc6b662b04

I can test with edmund's entire catalog once the fix is in.

You can get the catalog here if you want to try for yourself: https://www.edmundoptics.com/products/services/zemax-catalog/

**Comment by ajeddeloh** [comment]
Tested this and it works. Closing. Found some other bugs importing zmx files I'll PR fixes for.
